# Generated by Django 4.2.30 on 2026-06-08 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus_students', '0001_initial'),
        ('campus_finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campus_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='campus_students.student'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='campus_finance.feecategory'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='campus_core.classlevel'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='campus_core.academicterm'),
        ),
    ]
