# Generated by Django 4.2.30 on 2026-06-08 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Needs Repair', 'Needs Repair'), ('Damaged', 'Damaged')], default='Good', max_length=30)),
                ('date_acquired', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
